apiVersion: v1
kind: Service #object to be created
metadata:     #Info about object to be created
  name: my-nodeport-service   #Object name
spec:
  selector:     #Identifies the labels to match
    app: alma  # Name of the pod
  ports:
  - protocol: TCP  #type of traffic that the service listening for 
    port: 8080 #the port that the service is listening from
    targetPort: 80  #the port that the service is distributing to the pods
    #nodePort: 31000 # Optional; Kubernetes assigns one if omitted
  type: NodePort
#Access: 
#From outside the cluster via <NodeIP>:31000.
